# VidPly Extension - Dependency Injection Configuration

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mpc\MpcVidply\DataProcessing\:
    resource: '../Classes/DataProcessing/*'
    public: true

  Mpc\MpcVidply\DataProcessing\VidPlyProcessor:
    public: true
    autowire: true
